### ISSUE TITLE
Missing bottom padding

### ISSUE THREAD

**Issue by hannesbe** [bollewolle/delijn-card#8]
There seems to be some bottom padding missing? 

```
card:
  columns:
    - field: line_transport_type
      title: ' '
    - field: line_number_public
      title: Line
    - field: final_destination
      title: Towards
    - field: due_in_min
      title: In
    - field: due_at_realtime
      title: Real-time
    - field: due_at_schedule
      title: Scheduled
  config_type: columns
  entity: sensor.mas_antwerpen
  title: MAS
  type: 'custom:delijn-card'
conditions:
  - entity: sensor.mas_antwerpen
    state_not: unavailable
type: conditional
```

![image](https://user-images.githubusercontent.com/10950856/104926118-0a74d380-59a0-11eb-84ae-520b389181a4.png)
